//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class myfunctions {
  public static int add(int a, int b) {
    int ret = myfunctionsPINVOKE.add(a, b);
    return ret;
  }

  public static int multiply(int a, int b) {
    int ret = myfunctionsPINVOKE.multiply(a, b);
    return ret;
  }

}
